AWSTemplateFormatVersion: 2010-09-09
Description: >
  Create cloud formation templte with s3

Resources:
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-queue"
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-topic"
  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt SQSQueue.Arn
      Protocol: sqs
      TopicArn: !Ref SNSTopic
      
Outputs:
  QueueURL:
    Value: !Ref SQSQueue